version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: radar-rabbitmq
    tty: true
#    environment:
#      - RABBITMQ_DEFAULT_VHOST=radar
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "55672:15672"
    networks:
      - radar

  server:
    image: node:11-alpine
    container_name: radar-server
    tty: true
    volumes:
      - ../server:/var/www
    working_dir: /var/www
    entrypoint: node_modules/.bin/nodemon ./server.js --exec babel-node -e js
    links:
      - rabbitmq
    ports:
      - "4444:4000"
    environment:
      - RADAR_RABBITMQ_HOST=radar-rabbitmq
      - RADAR_RABBITMQ_PORT=5672
    networks:
      - radar

  client:
    image: node:11-alpine
    container_name: radar-client
    tty: true
    volumes:
      - ../client:/var/www
    working_dir: /var/www
    entrypoint: node_modules/.bin/react-scripts start
    ports:
      - "3333:3000"
    environment:
      - REACT_APP_RADAR_WS_URI=ws://radar-demo:4444/graphql
      - REACT_APP_RADAR_URI=http://radar-demo:4444/graphql
    links:
      - server
    networks:
      - radar
networks:
  radar:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.100.0/28"
