version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7-management-alpine
    container_name: radar-rabbitmq
    tty: true
#    environment:
#      - RABBITMQ_DEFAULT_VHOST=radar
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "55672:15672"

  server:
    image: node:11-alpine
    container_name: radar-server
    tty: true
    volumes:
      - ../server:/var/www
    working_dir: /var/www
    entrypoint: node_modules/.bin/nodemon ./server.js --exec babel-node -e js
    depends_on:
      - rabbitmq
      - client
    ports:
      - "4444:4000"
    environment:
      - RADAR_CLIENT_HOST=radar-demo
      - RADAR_CLIENT_PORT=3333
      - RADAR_SERVER_HOST=radar-demo
      - RADAR_SERVER_PORT=4444
      - RADAR_RABBITMQ_HOST=radar-rabbitmq
      - RADAR_RABBITMQ_PORT=5672
      - RADAR_SERVER_RUNNING_PORT=4000

  client:
    image: node:11-alpine
    container_name: radar-client
    tty: true
    volumes:
      - ../client:/var/www
    working_dir: /var/www
    entrypoint: node_modules/.bin/react-scripts start
    ports:
      - "3333:3000"
    environment:
      - REACT_APP_RADAR_SERVER_HOST=radar-demo
      - REACT_APP_RADAR_SERVER_PORT=4444
